name: Renovate dry-run

on:
  push:
    branches:
      - main
    paths:
      - "renovate.json5"
      - ".github/workflows/renovate-dry-run.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "renovate.json5"
      - ".github/workflows/renovate-dry-run.yaml"
jobs:
  renovate-dry-run:
    permissions:
      contents: read # required by actions/checkout
      pull-requests: read # required by renovate, because renovate to read pull request.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cybozu/renovate-dry-run-action@v1
        with:
          config-file: renovate.json5
