name: Renovate dry-run

on:
  push:
    branches:
      - main
    paths:
      - "renovate.json5"
      - ".github/workflows/renovate-dry-run.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "renovate.json5"
      - ".github/workflows/renovate-dry-run.yaml"
jobs:
  renovate-dry-run:
    permissions:
      contents: read # required by actions/checkout
      pull-requests: read # required by renovate, because renovate to read pull request.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - env:
          LOG_LEVEL: debug
          RENOVATE_DRY_RUN: full
        run: |
          # ref: https://docs.renovatebot.com/modules/platform/local/
          npx -y renovate --platform=local | tee ${{ runner.temp }}/renovate.log
      - name: Output logs to GITHUB_STEP_SUMMARY
        if: always()
        run: |
          echo "## Renovate Dry Run Logs" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`log" >> $GITHUB_STEP_SUMMARY
          cat renovate.log >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
